export const TOGGLE_PALETTE = 'TOGGLE_PALETTE';
export const CLEAR_PALETTES = 'CLEAR_PALETTES';

export const LAYOUT_GRID_PALETTE = 'LAYOUT_GRID_PALETTE';
export const BASELINE_GRID_PALETTE = 'BASELINE_GRID_PALETTE';
export const CONFIG_PALETTE = 'CONFIG_PALETTE';
