export const CLEAR_GUIDELINES = 'CLEAR_GUIDELINES';
export const CREATE_GUIDELINE = 'CREATE_GUIDELINE';
export const DELETE_GUIDELINE = 'DELETE_GUIDELINE';
export const DRAG_GUIDELINE = 'DRAG_GUIDELINE';
export const DROP_GUIDELINE = 'DROP_GUIDELINE';
